@startuml

class newYorkTicket
{
    plate
    issueDate
    infractionId
    fineAmount
    issuingAgency
}

class infractionsNYC
{
    id
    description
}

class chicagoTicket
{
    issueDate
    plateRedacted
    unitDescription
    infractionCode
    fineLevel1Amount
}

class infractionsCHI
{
    id
    description
}

class ticket
{
    char * plate
    char * date
    char * agency
    size_t fine
    size_t infractionID
    size_t index
}

newYorkTicket -- infractionsNYC
chicagoTicket -- infractionsCHI

' Ideas
class city
{
    car cars[]
    infractionSystem sytem;
}

class car
{
    char * plate
    size_t counter
    car *next
}

class agency
{
    char * name
    size_t len
    'vector of positions for tickets in city
    size_t qtyTickets
    size_t tickets[qtyTickets]
    size_t counterPerInfraction[qtyInfractions]
    agancy *next
}

class infraction
{
    size_t id
    size_t qty
    char * name
    car *carlist
}

class infractionSystem
{
    infraction infractions[]
    ticket tickets[]
    agency *agencyList
    size_t qtyInfractions
    size_t qtyTickets
    size_t qtyAgencies
}

infractionSystem -- agency
infractionSystem -- ticket
infractionSystem -- infraction
infraction -- car

@enduml