@startuml

class newYorkTicket
{
    plate
    issueDate
    infractionId
    fineAmount
    issuingAgency
}

class infractionsNYC
{
    id
    description
}

class chicagoTicket
{
    issueDate
    plateRedacted
    unitDescription
    infractionCode
    fineLevel1Amount
}

class infractionsCHI
{
    id
    description
}

newYorkTicket -- infractionsNYC
chicagoTicket -- infractionsCHI

class car
{
    char * plate
    size_t counter
    car *next
}

class agency
{
    char * name
    size_t qtyTickets
    infractionCounter counterPerInfraction[qtyInfractions]
    infractionCounter *max
    agancy *next
}

class infraction
{
    size_t id
    size_t qty
    char * name
    char vec[]
    car *carlist
    car *bigest
}

class infractionSystem
{
    infraction infractions[]
    agency *agencyList
    agency *currentAgency
    size_t idxActualInfraction
    size_t qtyInfractions
    size_t qtyTickets
    size_t qtyAgencies
}

infractionSystem -- agency
infractionSystem -- infraction
infraction -- car

@enduml