@startwbs

* main

** Backend
*** loadInfractions
*** exportToTicket
*** makeNewInfractionSystem
*** freeInfractionSystem
*** loadTicket
**** loadAgency
**** loadInfraction
***** loadCar
*** querry1
*** querry2
*** querry2

** Frontend
*** validateComandLine
*** validateFiles

@endwbs